export enum AttendanceStatus {
  PRESENT = "PRESENT",
  FAILED = "FAILED",
  CHECKED_OUT = "CHECKED_OUT",
}

export enum VerificationResult {
  MATCH = "MATCH",
  MISMATCH = "MISMATCH",
  UNKNOWN_CARD = "UNKNOWN_CARD",
  NO_FACE = "NO_FACE",
  NO_SESSION = "NO_SESSION",
  ERROR = "ERROR",
}

export enum LedFeedback {
  GREEN = "GREEN",
  RED = "RED",
  OFF = "OFF",
}

export enum BuzzerFeedback {
  SHORT_BEEP = "SHORT_BEEP",
  LONG_BEEP = "LONG_BEEP",
  NONE = "NONE",
}

export enum RoleName {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN_HR_ENROLLMENT = "ADMIN_HR_ENROLLMENT",
  PROFESSOR = "PROFESSOR",
}

export enum Permission {
  VIEW_DASHBOARD = "VIEW_DASHBOARD",
  VIEW_ATTENDANCE = "VIEW_ATTENDANCE",
  MANAGE_ATTENDANCE = "MANAGE_ATTENDANCE",
  VIEW_USERS = "VIEW_USERS",
  MANAGE_USERS = "MANAGE_USERS",
  ACCESS_ENROLLMENT = "ACCESS_ENROLLMENT",
  VIEW_CHARTS = "VIEW_CHARTS",
  ACCESS_VERIFICATION = "ACCESS_VERIFICATION",
  MANAGE_SETTINGS = "MANAGE_SETTINGS",
  MANAGE_ROLES = "MANAGE_ROLES",
  MANAGE_MASTER_DATA = "MANAGE_MASTER_DATA",
  MANAGE_MODULES = "MANAGE_MODULES",
  VIEW_OWN_STUDENTS = "VIEW_OWN_STUDENTS",
  VIEW_OWN_ATTENDANCE = "VIEW_OWN_ATTENDANCE",
}
